site_name: Ligato Docs
site_url: https://docs.ligato.io/
site_favicon: img/favicon.ico
site_description: Ligato documentation
site_author: Ligato Team

repo_url: https://github.com/ligato/docs

theme:
  name: rtd-dropdown
  custom_dir: custom/
  highlightjs: true
  hljs_languages:
    - go
    - yaml

extra_css:
  - css/extra.css

nav:
  - INTRODUCTION:
    - Overview: intro/overview.md
    - Framework: intro/framework.md
    - FAQ: intro/faq.md
  - USER GUIDE:
    - Quickstart Guide: user-guide/quickstart.md
    - VPP Agent Setup: user-guide/get-vpp-agent.md
    - Reference: user-guide/reference.md
    - Concepts: user-guide/concepts.md
    - Config Files: user-guide/config-files.md
    - AgentCtl: user-guide/agentctl.md
    - ARM64: user-guide/arm64.md
    - Examples: user-guide/examples.md
    - VPP CLI: user-guide/vpp-cli.md
  - TUTORIALS:
    - Setup: tutorials/00_tutorial-setup.md
    - Hello World: tutorials/01_hello-world.md
    - Plugin Dependencies: tutorials/02_plugin-deps.md
    - REST Handler: tutorials/03_rest-handler.md
    - KV Data Store: tutorials/04_kv-store.md
    - KV Scheduler: tutorials/05_kv-scheduler.md
    - Plugin Lookup: tutorials/06_plugin-lookup.md
    - VPP Connection: tutorials/07_vpp-connection.md
    - GRPC Handler: tutorials/08_grpc-tutorial.md
  - PLUGINS:
    - Plugin Overview: plugins/plugin-overview.md
    - KV Scheduler: plugins/kvs-plugin.md
    - VPP Plugins: plugins/vpp-plugins.md
    - Linux Plugins: plugins/linux-plugins.md
    - Connection Plugins: plugins/connection-plugins.md
    - Database Plugins: plugins/db-plugins.md
    - Infra Plugins: plugins/infra-plugins.md
  - DEVELOPER GUIDE:
    - Plugin Lookup: developer-guide/plugin-lookup.md
    - KV Scheduler: developer-guide/kvscheduler.md
    - KV Descriptors: developer-guide/kvdescriptor.md
    - KVS Troubleshooting: developer-guide/kvs-troubleshooting.md
    - Control Flows: developer-guide/control-flows.md
    - Model Registration: developer-guide/model-registration.md
    - Build VPP Agent + VPP with No Image: developer-guide/build-vpp-agent-no-image.md
    - Go Docs: developer-guide/godocs.md
  - Troubleshooting:
    - Start Up: troubleshooting/startup-ts.md
    - Configuration: troubleshooting/config-ts.md
  - TESTING:
    - Integration Tests: testing/integration-tests.md
    - Robot Framework Guide: testing/robot-framework-guide.md

markdown_extensions:
  - extra
  - admonition
  - smarty
  - codehilite:
      linenums: true
      use_pygments: false
  - sane_lists
  - toc:
      permalink: "#"
      baselevel: 3

