site_name: Ligato Docs
site_url: https://docs.ligato.io/
site_description: Ligato documentation
site_author: Ligato Team

repo_url: https://github.com/ligato/docs

theme:
  name: readthedocs
  custom_dir: custom/
  highlightjs: true
  hljs_languages:
    - go
    - yaml

extra_css:
  - css/extra.css

nav:
- INTRODUCTION:
  - VPP-Agent: intro/agent.md
  - CNF definition: intro/cnf-definition.md
  - Overview: intro/overview.md
  - CN-Infra: intro/cn-toc-file.md
- GETTING STARTED:
  - Get VPP-Agent: getting-started/get-vpp-agent.md
  - Quickstart guide: getting-started/quickstart.md
- FEATURES:
    - Concepts: features/concepts.md
    - References: features/references.md
    - ARM64: features/arm64.md
- PLUGINS:
  - Overview: plugins/plugin-overview.md
  - Core VPP plugins: plugins/core-vpp-plugins.md
  - Other VPP plugins: plugins/other-vpp-plugins.md
  - Linux plugins: plugins/linux-plugins.md
  - Connection plugins: plugins/connection-plugins.md
  - Database plugins: plugins/db-plugins.md
  - Framework plugins: plugins/framework-plugins.md
- DEVELOPER GUIDE:
  - Agent: developer-guide/agent.md
  - Plugin lookup: developer-guide/plugin-lookup.md
  - KV Scheduler: developer-guide/kvscheduler.md
  - KV Descriptors: developer-guide/kvdescriptor.md
  - KVS Problem Solving: developer-guide/problem-solving.md
  - Go Docs: developer-guide/godocs.md
- TUTORIALS:
  - Hello World: tutorials/01_hello-world.md
  - Plugin Dependencies: tutorials/02_plugin-deps.md
  - REST Handler: tutorials/03_rest-handler.md
  - KV Datastore: tutorials/04_kv-store.md
  - KV Scheduler: tutorials/05_kv-scheduler.md
  - Plugin Lookup: tutorials/06_plugin-lookup.md
  - VPP Connection: tutorials/07_vpp-connection.md
  - GRPC Handler: tutorials/08_grpc-tutorial.md
- TESTING:
  - CSIT tests locally: testing/tests-locally.md
  - Robot framework guide: testing/robot-framework-guide.md
- TOOLS:
    - VPP-Agent-Ctl: tools/vpp-agent-ctl.md
- TROUBLESHOOTING:
  - FAQ: troubleshooting/faq.md

markdown_extensions:
  - extra
  - admonition
  - smarty
#  - codehilite Note: disabled for now since it breaks code fences, will be re-enabled later
  - def_list
  - toc:
      permalink: ÔÉÅ
